const config = {
  DATABASE_URL_TEST: process.env.DATABASE_URL_TEST,
  DATABASE_URL_STAGING: process.env.DATABASE_URL_STAGING,
  DATABASE_URL_DEVELOPMENT: process.env.DATABASE_URL_DEVELOPMENT,
  DATABASE_URL_PRODUCTION: process.env.DATABASE_URL_PRODUCTION,
};

module.exports = config;
